### PR TITLE
Updates, fixes - request to maintain

### PR DESCRIPTION
**Pull request by pbrisbin**
Hi,

Thanks very much for the package, it's just what I need for my current project. In order to use it in my application I had to make a few changes and additions. I then went a bit further, refactoring, extending, using rather then duplicating `Network.OAuth.OAuth2`, etc.

I would love to take over as maintainer of this package and post it to Hackage. If not, please consider merging these changes and releasing the package.

Let me know your thoughts.

### CODE REVIEW

**Comment by pbrisbin** [comment]
Hi @scan 

> I'll try and get back into Yesod haskell programming, but if I give up I'll put ownership to you

I notice your involvement in this project has slowed and I've been handling most of the PRs and making my own changes etc. It hasn't been much, but I'd like to start doing more. Would you consider allowing me to move this repo to the thoughtbot org so other Haskellers at thoughtbot can more easily take part in maintaining this project?

I *think* if you increase my collaborator rights to Admin, I'll have permission to promote the repo to the organisation. If not, we'll have to think of something else.

Let me know, thanks.

**Comment by scan** [comment]
@pbrisbin I could not find how to change your collaborator status to Admin, it only lets me set you as collaborator or not. If you want to take over the project, you can. Perhaps it's better for you to fork it and I'll put a link to your fork?

I don't see myself participating much in this any more honestly, I kind of clinged on it for my portfolio. Now I will gladly hand it entirely over to you.

**Comment by scan** [comment]
@pbrisbin I tried to transfer the repository to you but you already have a fork, so it wouldn't let me.

**Comment by pbrisbin** [comment]
Hey thanks for trying! When I get back to a computer, probably Monday, I'll
delete my fork then we can try that path again.

**Comment by pbrisbin** [comment]
OK, I've deleted my fork.

**Pull request merged**
