### PR TITLE
Just some version bumps for stack 8.5 / ghc 8.x

### PR DESCRIPTION
**Pull request by adarqui**
Just a version bump for http-client and aeson. Worked on my end.

### CODE REVIEW

**Comment by halogenandtoast** [comment]
@adarqui is there a reason you closed this?

**Comment by adarqui** [comment]
@halogenandtoast nope.

**Comment by adarqui** [comment]
yup. done, thanks.

**Comment by sidraval** [comment]
Closing this, since https://github.com/thoughtbot/yesod-auth-oauth2/commit/d9ce2d334c01c82c9ab363e72222f0d3e8718f0b took care of it. Thanks all 😄

**Pull request closed without merging**
