### PR TITLE
Provider interface

### PR DESCRIPTION
**Pull request by pbrisbin**
Highlights:

- The "Provider" abstraction, which leads to
- Way tinier definitions, also aided by
- Stop fetching full profiles (#71)

---

In addition to general feedback on this, I plan to do the following before
merging:

- [ ] (Re-)document the heck out of all the modules
- [x] Backfill a bit of a CHANGELOG (so I have a good home to describe *this* major
  change)
- [ ] Go over lost functionality closely, and consider if anything should be
  preserved
- [ ] Take another shot at some kind of actual test suite (Maybe the new break-up
  of functionality can help here)

### CODE REVIEW

**Comment by pbrisbin** [comment]
Needless to say, the diff is rough to review (though the -600 LOC is pretty sweet). I'd recommend viewing the new code and judging things that way.

- https://github.com/thoughtbot/yesod-auth-oauth2/blob/d3fc380f16cc8ee3367d18bb10c23bb729ac1cc2/src/Yesod/Auth/OAuth2.hs
- https://github.com/thoughtbot/yesod-auth-oauth2/blob/d3fc380f16cc8ee3367d18bb10c23bb729ac1cc2/src/Yesod/Auth/OAuth2/Dispatch.hs
https://github.com/thoughtbot/yesod-auth-oauth2/blob/d3fc380f16cc8ee3367d18bb10c23bb729ac1cc2/src/Yesod/Auth/OAuth2/Upcase.hs (very simplest provider)
- https://github.com/thoughtbot/yesod-auth-oauth2/blob/d3fc380f16cc8ee3367d18bb10c23bb729ac1cc2/src/Yesod/Auth/OAuth2/Slack.hs (complex provider)

**Comment by mwu** [comment]
Sorry and I don't mean to butt in but I was using this plugin and stumbled on this pull request. I know it's a WIP, but are there any plans on adding two final decoders for the remaining credsExtra entries, ie `decodeAccessToken :: Creds m -> AccessToken` and `userResponseBody :: Creds m -> Text` or something similar just to take the burden from client code?

Along the same lines, now that clients are more likely to do further fetches in authenticate, should the providers export their names so client code doesn't need to do something like `authenticate c = case credsPlugin c of "github" -> ...; "spotify" -> ...` which feels wrong? I noticed yesod-auth's GoogleEmail2 exports a  [pid](https://hackage.haskell.org/package/yesod-auth-1.4.21/docs/Yesod-Auth-GoogleEmail2.html#v:pid). Seems to be the only plugin that does, though....

Anyway, these changes make using this package a lot easier, so thank you.

**Comment by pbrisbin** [comment]
@mwu thanks a ton for joining in and providing feedback! With such a large change, it's important to me to have some sense that it's a move in the right direction.

> are there any plans on adding two final decoders for the remaining credsExtra entries, ie decodeAccessToken :: Creds m -> AccessToken and userResponseBody :: Creds m -> Text or something similar just to take the burden from client code?

I wasn't planning on that, because the functions would be so simple:

```hs
decodeAccessToken :: Creds m -> Maybe AccessToken
decodeAccessToken = AccessToken <$> lookup "accessToken" . credsExtra

userResponseBody :: Creds m -> Maybe Text
userResponseBody = lookup "userResponseJson" . credsExtra

-- Or perhaps
userResponse :: FromJSON a => Creds m -> Maybe a
userResponse = decode . BL.decodeUtf8 <=< lookup "userResponseJson" . credsExtra
```

If you think it would be useful to provide these, I have no issue adding them.

> now that clients are more likely to do further fetches in authenticate, should the providers export their names

My ultimate goal is that `Provider` is the main API of this package. So in `Foundation`, you might do something like:

```hs
authPlugins = [oauth2Plugin githubProvider cid cs]
```

And you can use `pName githubProvider` anywhere you needed to recover `"github"`. This is the main reason why I don't want you to have to pass the client id/secret just to construct a `Provider` -- `oauth2Plugin` accepts those and puts them together with the provider details at dispatch-time.

This PR is a bit experimental, so as I implement it in stages, there may be times this isn't quite the case yet, but it's where I'm aiming.

> these changes make using this package a lot easier

Are you actually using this branch in a project? I'd be great to know that it's working (we lack pretty much any sort of testing here), and I'm glad to hear the new API is actually easier!

**Comment by mwu** [comment]
Ok let's all avert our eyes a little, because it's pretty rough and I only had a few minutes to play with this last night: https://github.com/mwu/gitit2/commit/8e7518e0ac7b2d847554a7f962906205137cbaa6 But yes, it does work. I haven't yet changed the login widget, but that I can do so is why I was saying this is nicer, among other reasons.

That makes sense now about not needing to repeat the plugin names as literals. For some reason last night it didn't occur to me to define the provider outside the instance definition. The decoder for accessToken I wanted as Creds m -> Text because I'd argue that isn't a real Maybe, but I'm probably just being lazy and trying to throw you a fromJust hot potato. I can't think of anything I'd do with the Nothing case other than throw a generic error, but I grant that I then have the choice as a user what to do with it. It just seems like a lot of ceremony when we're fairly sure it's not going to be a Nothing. The key name's also under your control rather than mine and it's already changed once now, so it's also a bit of a DRY thing 😉

**Comment by mwu** [comment]
Oh and I'm not sure if I detected a hint of worry in your comment, but I'm not using this for work or anything about to go into production. I'm just trying to see how to add oauth to gitit2 which isn't being actively developed. So I'm not rushing to use this, I have whatever time I need to watch this PR and uhhh de-uglify the commit I linked to 😝

**Comment by pbrisbin** [comment]
Thanks so much for providing that context! My plan is to let this PR idle and bring pieces of it slowing in through other, smaller PRs -- rebasing this one along the way until it's reduced to something more manageable.

Adding those decoders would probably be some icing that happens _after_ that long slog of PRs, so we can discuss further the better interface there. I'm not against a `fromJust` when I'm accessing data I've put there myself in the same library, so we'll see.

**Comment by pbrisbin** [comment]
This has served its purpose. I'm going to focus on #100 and follow-up (perhaps) with such a `Provider` abstraction after that's landed.

**Pull request closed without merging**
