### PR TITLE
Switch to newer Nylas API endpoint

### PR DESCRIPTION
**Pull request by bts**
Hi there,

Nylas just updated their API today, and the existing endpoint (`/n`, for "namespace") we were using will unfortunately be decommissioned sometime after October 1, 2015. This patch switches to their new `/account` endpoint.

There are no changes to the types of the user-facing `oauth2Nylas` or `oauth2NylasScoped` functions, but we now no longer return one of the entries in `credsExtra`: what Nylas _used to_ call the `account_id`, but wasn't actually used for anything. Nylas has stopped serving this older notion of `account_id`, and now returns what was called the `namespace_id` as `account_id`. We're still returning the user this same value as our `credsIdent`.

Let me know if you have any questions.

Thanks!
Brian

### CODE REVIEW

**Comment by jferris** [comment]
This looks good to me.

@pbrisbin any objections to merging this in?

**Comment by pbrisbin** [comment]
Nope. Go for it.

**Comment by jferris** [comment]
Thanks! I merged this into master.

**Comment by bts** [comment]
Thank you!

**Pull request closed without merging**
